services:
  # VERİTABANI
  db:
    image: mongo:latest
    container_name: easystock_db
    ports:
      - "27017:27017"
    networks:
      - easystock-network

  # BACKEND (REST API)
  backend:
    build: ./easystock-api
    container_name: easystock_api_kapsayici
    ports:
      - "9000:9000"
    depends_on:
      - db
    networks:
      - easystock-network

  # FRONTEND
  frontend:
    build: ./easystock-frontend
    container_name: easystock_front_kapsayici
    ports:
      - "3000:80" # Bilgisayardaki 3000 -> Docker içindeki 80
    depends_on:
      - backend
    networks:
      - easystock-network
    volumes:
      - ./easystock-frontend:/usr/share/nginx/html # Bilgisayardaki değişimi anında Docker'a iletir

networks:
  easystock-network:
    driver: bridge