# 1. Hafif bir web sunucusu (Nginx) kullanıyoruz
FROM nginx:alpine

# 2. index.html dosyanı sunucunun ana klasörüne kopyalıyoruz
COPY index.html /usr/share/nginx/html/index.html

# 3. Web trafiği için 80 portunu açıyoruz
EXPOSE 80